#theme: jekyll-theme-leap-day
theme: Minima
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
#remote_theme: cotes2020/jekyll-theme-chirpy
#remote_theme: Huxpro/huxpro.github.io